void affichage(int t[],int taille);
int sommeElements(int t[],int taille);
int maxOuMin(int t[],int taille,char type);
bool chercher(int t[],int taille,int valeur);
void chercherPlusieursValeurs(int t[],int taille,int vals[],int nb);
bool estPremier(int a);
int * obtenirNombresPremiers(int t[],int taille);
int nbChiffre(int a);
bool estPalindrome(int a);
int * obtenirNombresPalindrome(int t[],int taille);
void mettre_a_jour(int t[],int taille,int pos,int val);
int inserer(int t[],int taille,int val,int pos);
int insererSansDoublon(int t[],int taille,int val,int pos);
int supprimer(int t[],int taille,int val);
int supprimerTousLesDoublons(int t[],int taille,int val);
void tri(int t[],int taille,char type);
int* fusion(int t1[],int taille1,int t2[],int taille2);
int* fusionTriee(int t1[],int taille1,int t2[],int taille2);
char* convert(int val,int base);
